name: Process and sync profiles
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 18 * * *'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    tags-ignore:
      - sync
  workflow_dispatch:
env:
  TRASH_GUIDES_DIRECTORY: 'trash-guides'
  DICTIONARRY_DATABASE_DIRECTORY: 'dictionarry-database'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v5
        
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.7'
          
      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Checkout Dictionarry database repository
        uses: actions/checkout@v5
        with:
          repository: Dictionarry-Hub/database
          ref: stable
          path: ${{ env.DICTIONARRY_DATABASE_DIRECTORY }}

      - name: Checkout TRaSH guides repository
        uses: actions/checkout@v5
        with:
          repository: TRaSH-Guides/Guides
          ref: master
          path: ${{ env.TRASH_GUIDES_DIRECTORY }}

      - name: Sync Dictionarry changes
        run: |
          rsync -av --delete ${{ env.DICTIONARRY_DATABASE_DIRECTORY }}/custom_formats/ custom_formats
          rsync -av --delete ${{ env.DICTIONARRY_DATABASE_DIRECTORY }}/media_management/ media_management
          rsync -av --delete ${{ env.DICTIONARRY_DATABASE_DIRECTORY }}/profiles/ profiles
          rsync -av --delete ${{ env.DICTIONARRY_DATABASE_DIRECTORY }}/regex_patterns/ regex_patterns

      - name: Process TRaSH guides
        run: |
          python scripts/trash_custom_format_id_mapper.py ${{ env.TRASH_GUIDES_DIRECTORY }}
          python scripts/trash_custom_format_parser.py ${{ env.TRASH_GUIDES_DIRECTORY }}
          python scripts/trash_profile_parser.py ${{ env.TRASH_GUIDES_DIRECTORY }}

      - name: Commit any changes
        id: commit_changes
        run: |
          git add custom_formats/*.yml media_management/*.yml profiles/*.yml regex_patterns/*.yml
          if git diff --exit-code --staged; then
            echo "No changes detected, nothing will be merged."
            echo "committed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Merge all database changes"
            echo "committed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create (or update) pull request
        if: steps.commit_changes.outputs.committed == 'true'
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          title: Update to Dictionarry database
          commit-message: |
            Sync changes from Dictionarry [skip ci]
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: sync-latest
          base: ${{ steps.extract_branch.outputs.branch }}
          add-paths: |
            custom_formats/*.yml
            media_management/*.yml
            profiles/*.yml
            regex_patterns/*.yml
          labels: |
            sync

      - name: Merge PR
        if: github.ref == 'refs/heads/main'
          && steps.commit_changes.outputs.committed == 'true'
          && (steps.pr.outputs.pull-request-operation == 'created' || steps.pr.outputs.pull-request-operation == 'updated' || steps.pr.outputs.pull-request-number)
        run: |
          gh pr merge ${{ steps.pr.outputs.pull-request-number }} --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.PAT }}